import { Asset } from 'expo-asset';

export const BIBLE_ASSETS: Record<string, any> = {
  '1': require('../assets/amharic/01-genesis.json'),
  '2': require('../assets/amharic/02-exodus.json'),
  '3': require('../assets/amharic/03-leviticus.json'),
  '4': require('../assets/amharic/04-numbers.json'),
  '5': require('../assets/amharic/05-deuteronomy.json'),
  '6': require('../assets/amharic/06-joshua.json'),
  '7': require('../assets/amharic/07-judges.json'),
  '8': require('../assets/amharic/08-ruth.json'),
  '9': require('../assets/amharic/09-1samuel.json'),
  '10': require('../assets/amharic/10-2 samuel.json'),
  '11': require('../assets/amharic/11-1 kings.json'),
  '12': require('../assets/amharic/12-2 kings.json'),
  '13': require('../assets/amharic/13-1 chronicles.json'),
  '14': require('../assets/amharic/14-2 chronicles.json'),
  '15': require('../assets/amharic/15-kufale.json'),
  '16': require('../assets/amharic/16-enoch.json'),
  '17': require('../assets/amharic/17-ezra.json'),
  '18': require('../assets/amharic/18-nehemiah.json'),
  '19': require('../assets/amharic/19-ezrasutuel.json'),
  '20': require('../assets/amharic/20-ezrakale.json'),
  '21': require('../assets/amharic/21-tobit.json'),
  '22': require('../assets/amharic/22-yodit.json'),
  '23': require('../assets/amharic/23-esther.json'),
  '24': require('../assets/amharic/24-1 maccabees.json'),
  '25': require('../assets/amharic/25-2 maccabees.json'),
  '26': require('../assets/amharic/26-3 maccabees.json'),
  '27': require('../assets/amharic/27-job.json'),
  '28': require('../assets/amharic/28-psalms.json'),
  '29': require('../assets/amharic/29-proverbs.json'),
  '30': require('../assets/amharic/30-admonition.json'),
  '31': require('../assets/amharic/31-wisdom of solomon.json'),
  '32': require('../assets/amharic/32-ecclesiastes.json'),
  '33': require('../assets/amharic/33-song of solomon.json'),
  '34': require('../assets/amharic/34-sirach.json'),
  '35': require('../assets/amharic/35-isaiah.json'),
  '36': require('../assets/amharic/36-jeremiah.json'),
  '37': require('../assets/amharic/37-Baruch.json'),
  '38': require('../assets/amharic/38-lamentations.json'),
  '39': require('../assets/amharic/39-terefermias.json'),
  '40': require('../assets/amharic/40-Teref Baruch.json'),
  '41': require('../assets/amharic/41-ezekiel.json'),
  '42': require('../assets/amharic/42-daniel.json'),
  '43': require('../assets/amharic/43-hosea.json'),
  '44': require('../assets/amharic/44-amos.json'),
  '45': require('../assets/amharic/45-micah.json'),
  '46': require('../assets/amharic/46-joel.json'),
  '47': require('../assets/amharic/47-obadiah.json'),
  '48': require('../assets/amharic/48-jonah.json'),
  '49': require('../assets/amharic/49-nahum.json'),
  '50': require('../assets/amharic/50-habakkuk.json'),
  '51': require('../assets/amharic/51-zephaniah.json'),
  '52': require('../assets/amharic/52-haggai.json'),
  '53': require('../assets/amharic/53-zechariah.json'),
  '54': require('../assets/amharic/54-malachi.json'),
  '55': require('../assets/amharic/55-matthew.json'),
  '56': require('../assets/amharic/56-mark.json'),
  '57': require('../assets/amharic/57-luke.json'),
  '58': require('../assets/amharic/58-john.json'),
  '59': require('../assets/amharic/59-act.json'),
  '60': require('../assets/amharic/60-romans.json'),
  '61': require('../assets/amharic/61-1_corinthians.json'),
  '62': require('../assets/amharic/62-2_corinthians.json'),
  '63': require('../assets/amharic/63-galatians.json'),
  '64': require('../assets/amharic/64-ephesians.json'),
  '65': require('../assets/amharic/65-philippians.json'),
  '66': require('../assets/amharic/66-colossians.json'),
  '67': require('../assets/amharic/67-1_thessalonians.json'),
  '68': require('../assets/amharic/68-2_thessalonians.json'),
  '69': require('../assets/amharic/69-1_timothy.json'),
  '70': require('../assets/amharic/70-2_timothy.json'),
  '71': require('../assets/amharic/71-titus.json'),
  '72': require('../assets/amharic/72-philemon.json'),
  '73': require('../assets/amharic/73-hebrews.json'),
  '74': require('../assets/amharic/74-1_peter.json'),
  '75': require('../assets/amharic/75-2_peter.json'),
  '76': require('../assets/amharic/76-1_john.json'),
  '77': require('../assets/amharic/77-2_john.json'),
  '78': require('../assets/amharic/78-3-john.json'),
  '79': require('../assets/amharic/79-james.json'),
  '80': require('../assets/amharic/80-jude.json'),
  '81': require('../assets/amharic/81-revelation.json'),
};
